
<?php 

$helper = $this->getHelper();
$registry = $this->simiObjectManager->get('\Magento\Framework\Registry');


?>

<?php if ($helper->getStoreConfig("simifbconnect/general/enable")): ?>
    <?php $_product = $registry->registry('current_product'); ?>
    <?php if ($_product) : ?>
        <?php 
        $androidIdentifyKey = $helper->getStoreConfig("simifbconnect/general/android_identify_key");
        $iOSIdentifyKey = $helper->getStoreConfig("simifbconnect/general/ios_identify_key");
        $urlAndroid = str_replace(".", "", $androidIdentifyKey).'://product_id='.$_product->getId();
        $urliOS = str_replace(".", "", $iOSIdentifyKey).'://product_id='.$_product->getId()
        ?>

        <meta property="al:ios:url" content="<?php echo $urliOS ?>" />
        <meta property="al:ios:app_store_id" content="<?php echo $helper->getStoreConfig("simifbconnect/general/ios_app_id") ?>" />
        <meta property="al:ios:app_name" content="<?php echo $helper->getStoreConfig("simifbconnect/general/ios_appname") ?>" />

        <meta property="al:android:url" content="<?php echo $urlAndroid ?>" />
        <meta property="al:android:package" content="<?php echo $helper->getStoreConfig("simifbconnect/general/android_identify_key") ?>" />
        <meta property="al:android:app_name" content="<?php echo $helper->getStoreConfig("simifbconnect/general/android_appname") ?>" />

        <meta property="og:title" content="<?php echo $_product->getName() ?>" />
        <meta property="og:type" content="website" />
        <meta property="al:web:should_fallback" content="false" />
        <meta property="fb_product_id" content="<?php echo $_product->getId() ?>" />
    <?php endif; ?>
<?php endif; ?>