<?php $url = Mage::getStoreConfig("simipromoteapp/popup/link_alert"); ?>
<?php $message = Mage::getStoreConfig("simipromoteapp/popup/content_alert"); ?>
<?php $typeShow = Mage::getStoreConfig("simipromoteapp/popup/show_type"); ?>
<?php if (Mage::getStoreConfig("simipromoteapp/popup/enable") == 1 && $url != '' && $message != ''): ?>
    <script type="text/javascript">
        function getCookie(c_name) {
            if (document.cookie.length > 0) {
                c_start = document.cookie.indexOf(c_name + "=");
                if (c_start != -1) {
                    c_start = c_start + c_name.length + 1;
                    c_end = document.cookie.indexOf(";", c_start);
                    if (c_end == -1) {
                        c_end = document.cookie.length;
                    }
                    return unescape(document.cookie.substring(c_start, c_end));
                }
            }
            return "";
        }

        document.observe("dom:loaded", function() {
            var isMobile = false;
            var url = '';
            if (navigator.userAgent.match(/Android/i)) {
                isMobile = true;
                url = '<?php echo Mage::getStoreConfig("simipromoteapp/popup/link_android"); ?>';
            }
            if (navigator.userAgent.match(/iPhone/i)) {
                isMobile = true;
                url = '<?php echo Mage::getStoreConfig("simipromoteapp/popup/link_ipad"); ?>';
            }
            if (navigator.userAgent.match(/iPad/i)) {
                isMobile = true;
                url = '<?php echo Mage::getStoreConfig("simipromoteapp/popup/link_alert"); ?>';
            }
            // initially hide all containers for tab content
            if (getCookie('SessionSimiPopup') != '1')
                if (isMobile) {
                    var r = confirm("<?php echo $message; ?>");
                    if (r == true)
                    {
                        setLocation(url);
                    }
					var name = 'SessionSimiPopup';
					var value = '1';
					document.cookie = name + "=" + value;
                }
        });

    </script>
<?php endif; ?>