<div class="landing-shop-page">
<div id="download-app" class="section-01">
<div class="wrap-background">
<div class="container">
<div class="row">
<div class="col-md-7 col-sm-6">
<div class="title-page">Shop right on the palm of your hand!</div>
<div class="sub-title-page">
<div class="row">
<div class="col-md-9">It's super-easy, quick &amp;
convenient to shop for your desired items via mobile apps effortlessly anywhere, anytime.
<br />Never miss out on that latest item and best promotion deals again.
<br />Hurry up and enjoy shopping with our mobile apps today!</div>
</div>
</div>
<div class="download-icon">
<div class="row">
<div class="col-md-5 col-sm-8">
<div class="button-actions"><a class="ios-button" href="#"><span class="wrap-a"><strong>Download App</strong>
<span>From App Store</span></span></a> <a class="android-button" href="#"><span class="wrap-a">
<strong>Download App</strong><span>From Play Store</span></span></a></div>
</div>
<div class="col-md-4 col-sm-8">
<div class="wrap-qr"><img title="" src="<?php echo $block->getViewFileUrl('Simi_Simipromoteapp::images/qr-code.png') ?>" alt="" />
<span class="title-qr-code">Scan to download this app</span></div>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-sm-6 col-md-offset-1">
<div class="wrap-image"><?php echo $block->getImageHtml('1') ?></div>
</div>
</div>
</div>
</div>
</div>
<div class="section-02">
<div class="wrap-background">
<div class="container">
<div class="row">
<div class="col-md-6 col-sm-7">
<div class="wrap-image"><?php echo $block->getImageHtml('2') ?></div>
</div>
<div class="col-md-6 col-sm-5">
<h3 class="title-box">Shop at Young FingerTips with Ease</h3>
<ul>
<li><span>Easily browse over hundreds of items in our catalog.</span></li>
<li><span>Our filters make it simple to find exactly what you want. </span></li>
<li><span>Sort by brand, category, size, colour and price.</span></li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div class="section-03">
<div class="wrap-background">
<div class="container">
<div class="row">
<div class="col-md-5">
<h3 class="title-box">Never Miss Best Deals <br />and All Latest Items</h3>
<span>Get instant updates on the latest products, hottest trends and offers personalized for your interest!
 Not only is it time efficient but you can experience the same feel of shopping on the go.</span></div>
<div class="col-md-6 col-md-offset-1">
<div class="wrap-image"><?php echo $block->getImageHtml('4') ?>
<div class="more-image"><?php echo $block->getImageHtml('3') ?></div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="section-04">
<div class="wrap-background">
<div class="container">
<div class="row">
<div class="col-md-12">
<h3 class="title-box">Checkout Quickly and Safely</h3>
<span class="title-sub">Order your new goodies with fast, safe and convenient payment methods: cash-on-delivery,
credit card, bank transfer, PayPal, 2Checkout and more.</span></div>
<div class="col-md-4">
<div class="wrap-image"><?php echo $block->getImageHtml('5') ?></div>
</div>
<div class="col-md-4">
<div class="wrap-image2"><img class="second-img" title="" src="<?php echo $block->getViewFileUrl('Simi_Simipromoteapp::images/bg-image-04-02.png') ?>"
alt="" /></div>
</div>
<div class="col-md-4">
<div class="wrap-image3"><img class="third-img" title="" src="<?php echo $block->getViewFileUrl('Simi_Simipromoteapp::images/bg-image-04-03.png') ?>"
alt="" /></div>
</div>
</div>
</div>
</div>
</div>
<div class="section-05">
<div class="wrap-background">
<div class="container">
<div class="row">
<div class="col-md-12">
<h3 class="title-box">Let Us Be With You Anytime, Anywhere!</h3>
<div class="actions"><a title="Get App Now" href="#download-app"><span>Get App Now</span></a></div>
</div>
</div>
</div>
</div>
</div>
</div>