<?php if ($this->isEnable()): ?>

    <?php
    $_pointHelper = $this->getPointHelper();
    $_spendingPoint = $this->getSpendingPoint();
    $_earningPoints = $this->getEarningPoint();
    $_earningPointsByCoupon = $this->helper('Simi\Simirewardpoints\Helper\Calculation\Earning')->getEarningPointByCoupon();
    ?>
    <?php if ($_spendingPoint || $_earningPoints  || $_earningPointsByCoupon): ?>
        <?php if ($this->getColspan() == 1): ?><thead><?php endif ?>
        <?php if ($_spendingPoint): ?>
            <tr class="row-totals">
                <td class="a-right" id="check-spend-point" colspan="<?php echo $this->getColspan() ?>" style="<?php echo $this->getTotal()->getStyle() ?>">
                    <strong style="font-size: 13px;">
                        <?php

                            echo __('You will spend');

                        ?>:</strong>
                </td>
                <td class="a-right" style="min-width: 70px;text-align:right;<?php echo $this->getTotal()->getStyle() ?>">
                    <?php echo $_pointHelper->format($_spendingPoint) ?>
                </td>
            </tr>
        <?php endif ?>
        <?php if ($_earningPoints): ?>
            <tr>
                <td class="a-right" colspan="<?php echo $this->getColspan() ?>" style="<?php echo $this->getTotal()->getStyle() ?>">
                    <strong style="font-size: 13px;">
                        <?php
                            if($this->getQuote()->getCustomerGroupId() > 0){
                                echo __('You will earn');
                            } ?>:</strong>
                </td>
                <td class="a-right" style="min-width: 70px;text-align:right;<?php echo $this->getTotal()->getStyle() ?>">
                    <?php echo $_pointHelper->format($_earningPoints) ?>
                </td>
            </tr>
        <?php endif ?>
        <?php if ($_earningPointsByCoupon): ?>
            <tr>
                <td class="a-right" colspan="<?php echo $this->getColspan() ?>" style="<?php echo $this->getTotal()->getStyle() ?>">
                    <?php echo __('Earn Points (%1)', $this->helper('Simi\Simirewardpoints\Helper\Calculation\Earning')->getCouponEarnPoints()); ?>
                </td>
                <td class="a-right" style="min-width: 70px;text-align:right;<?php echo $this->getTotal()->getStyle() ?>">
                    <?php echo $_pointHelper->format($_earningPointsByCoupon) ?>
                </td>
            </tr>
        <?php endif ?>
        <?php if ($this->getColspan() == 1): ?></thead><?php endif ?>
    <?php endif ?>

    <?php

endif // End if ($this->isEnable()) ?>
