<?php /* @var $block \Simi\Simipwa\Block\System\Config\Form\SyncButton */ ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {

        var collectSpan = jQuery('#collect_span');

        jQuery('#clear_mobile_cache').click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                method: 'GET'
                onCreate: function () {
                    collectSpan.find('.processing').show();
                    jQuery('#collect_message_span').text('');
                },
                onSuccess: function (response) {
                    collectSpan.find('.processing').hide();
                    console.log(response);
                    if (response.status > 200) {
                        alert('Something went wrong!');
                    } else {
                        var json = response.responseJSON;
                        alert('Completed!')
                    }
                }
            });
        });
    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="collect-indicator" id="collect_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px"
         src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <span id="collect_message_span"></span>
</span>