<?php

class Simi_Simistorelocator_Model_System_Config_Language {

    public function toOptionArray() {
        $options = array(
            array('value' => 'ca_ES', 'label' => Mage::helper('simistorelocator')->__('Catalan')),
            array('value' => 'cs_CZ', 'label' => Mage::helper('simistorelocator')->__('Czech')),
            array('value' => 'cy_GB', 'label' => Mage::helper('simistorelocator')->__('Welsh')),
            array('value' => 'da_DK', 'label' => Mage::helper('simistorelocator')->__('Danish')),
            array('value' => 'de_DE', 'label' => Mage::helper('simistorelocator')->__('German')),
            array('value' => 'eu_ES', 'label' => Mage::helper('simistorelocator')->__('Basque')),
            array('value' => 'en_PI', 'label' => Mage::helper('simistorelocator')->__('English (Pirate)')),
            array('value' => 'en_UD', 'label' => Mage::helper('simistorelocator')->__('English (Upside Down)')),
            array('value' => 'ck_US', 'label' => Mage::helper('simistorelocator')->__('Cherokee')),
            array('value' => 'en_US', 'label' => Mage::helper('simistorelocator')->__('English (US)')),
            array('value' => 'es_LA', 'label' => Mage::helper('simistorelocator')->__('Spanish')),
            array('value' => 'es_CL', 'label' => Mage::helper('simistorelocator')->__('Spanish (Chile)')),
            array('value' => 'es_CO', 'label' => Mage::helper('simistorelocator')->__('Spanish (Colombia)')),
            array('value' => 'es_ES', 'label' => Mage::helper('simistorelocator')->__('Spanish (Spain)')),
            array('value' => 'es_MX', 'label' => Mage::helper('simistorelocator')->__('Spanish (Mexico)')),
            array('value' => 'es_VE', 'label' => Mage::helper('simistorelocator')->__('Spanish (Venezuela)')),            
            array('value' => 'fi_FI', 'label' => Mage::helper('simistorelocator')->__('Finnish')),
            array('value' => 'fr_FR', 'label' => Mage::helper('simistorelocator')->__('French (France)')),
            array('value' => 'gl_ES', 'label' => Mage::helper('simistorelocator')->__('Galician')),
            array('value' => 'hu_HU', 'label' => Mage::helper('simistorelocator')->__('Hungarian')),
            array('value' => 'it_IT', 'label' => Mage::helper('simistorelocator')->__('Italian')),
            array('value' => 'ja_JP', 'label' => Mage::helper('simistorelocator')->__('Japanese')),
            array('value' => 'ko_KR', 'label' => Mage::helper('simistorelocator')->__('Korean')),
            array('value' => 'nb_NO', 'label' => Mage::helper('simistorelocator')->__('Norwegian (bokmal)')),
            array('value' => 'nn_NO', 'label' => Mage::helper('simistorelocator')->__('Norwegian (nynorsk)')),
            array('value' => 'nl_NL', 'label' => Mage::helper('simistorelocator')->__('Dutch')),
            array('value' => 'pl_PL', 'label' => Mage::helper('simistorelocator')->__('Polish')),
            array('value' => 'pt_BR', 'label' => Mage::helper('simistorelocator')->__('Portuguese (Brazil)')),
            array('value' => 'pt_PT', 'label' => Mage::helper('simistorelocator')->__('Portuguese (Portugal)')),
            array('value' => 'ro_RO', 'label' => Mage::helper('simistorelocator')->__('Romanian')),
            array('value' => 'ru_RU', 'label' => Mage::helper('simistorelocator')->__('Russian')),
            array('value' => 'sk_SK', 'label' => Mage::helper('simistorelocator')->__('Slovak')),
            array('value' => 'sl_SI', 'label' => Mage::helper('simistorelocator')->__('Slovenian')),
            array('value' => 'sv_SE', 'label' => Mage::helper('simistorelocator')->__('Swedish')),
            array('value' => 'th_TH', 'label' => Mage::helper('simistorelocator')->__('Thai')),
            array('value' => 'ku_TR', 'label' => Mage::helper('simistorelocator')->__('Kurdish')),
            array('value' => 'zh_CN', 'label' => Mage::helper('simistorelocator')->__('Simplified Chinese (China)')),
            array('value' => 'zh_HK', 'label' => Mage::helper('simistorelocator')->__('Traditional Chinese (Hong Kong)')),
            array('value' => 'zh_TW', 'label' => Mage::helper('simistorelocator')->__('Traditional Chinese (Taiwan)')),
            array('value' => 'fb_LT', 'label' => Mage::helper('simistorelocator')->__('Leet Speak')),
            array('value' => 'af_ZA', 'label' => Mage::helper('simistorelocator')->__('Afrikaans')),
            array('value' => 'sq_AL', 'label' => Mage::helper('simistorelocator')->__('Albanian')),
            array('value' => 'hy_AM', 'label' => Mage::helper('simistorelocator')->__('Armenian')),
            array('value' => 'az_AZ', 'label' => Mage::helper('simistorelocator')->__('Azeri')),
            array('value' => 'be_BY', 'label' => Mage::helper('simistorelocator')->__('Belarusian')),
            array('value' => 'bn_IN', 'label' => Mage::helper('simistorelocator')->__('Bengali')),
            array('value' => 'bs_BA', 'label' => Mage::helper('simistorelocator')->__('Bosnian')),
            array('value' => 'bg_BG', 'label' => Mage::helper('simistorelocator')->__('Bulgarian')),
            array('value' => 'hr_HR', 'label' => Mage::helper('simistorelocator')->__('Croatian')),
            array('value' => 'nl_BE', 'label' => Mage::helper('simistorelocator')->__('Dutch (Belgie)')),
            array('value' => 'en_GB', 'label' => Mage::helper('simistorelocator')->__('English (UK)')),
            array('value' => 'eo_EO', 'label' => Mage::helper('simistorelocator')->__('Esperanto')),
            array('value' => 'et_EE', 'label' => Mage::helper('simistorelocator')->__('Estonian')),
            array('value' => 'fo_FO', 'label' => Mage::helper('simistorelocator')->__('Faroese')),
            array('value' => 'fr_CA', 'label' => Mage::helper('simistorelocator')->__('French (Canada)')),
            array('value' => 'ka_GE', 'label' => Mage::helper('simistorelocator')->__('Georgian')),
            array('value' => 'el_GR', 'label' => Mage::helper('simistorelocator')->__('Greek')),
            array('value' => 'gu_IN', 'label' => Mage::helper('simistorelocator')->__('Gujarati')),
            array('value' => 'hi_IN', 'label' => Mage::helper('simistorelocator')->__('Hindi')),
            array('value' => 'is_IS', 'label' => Mage::helper('simistorelocator')->__('Icelandic')),
            array('value' => 'id_ID', 'label' => Mage::helper('simistorelocator')->__('Indonesian')),
            array('value' => 'ga_IE', 'label' => Mage::helper('simistorelocator')->__('Irish')),
            array('value' => 'jv_ID', 'label' => Mage::helper('simistorelocator')->__('Javanese')),
            array('value' => 'kn_IN', 'label' => Mage::helper('simistorelocator')->__('Kannada')),
            array('value' => 'kk_KZ', 'label' => Mage::helper('simistorelocator')->__('Kazakh')),
            array('value' => 'la_VA', 'label' => Mage::helper('simistorelocator')->__('Latin')),
            array('value' => 'lv_LV', 'label' => Mage::helper('simistorelocator')->__('Latvian')),
            array('value' => 'li_NL', 'label' => Mage::helper('simistorelocator')->__('Limburgish')),
            array('value' => 'lt_LT', 'label' => Mage::helper('simistorelocator')->__('Lithuanian')),
            array('value' => 'mk_MK', 'label' => Mage::helper('simistorelocator')->__('Macedonian')),
            array('value' => 'mg_MG', 'label' => Mage::helper('simistorelocator')->__('Malagasy')),
            array('value' => 'ms_MY', 'label' => Mage::helper('simistorelocator')->__('Malay')),
            array('value' => 'mt_MT', 'label' => Mage::helper('simistorelocator')->__('Maltese')),
            array('value' => 'mr_IN', 'label' => Mage::helper('simistorelocator')->__('Marathi')),
            array('value' => 'mn_MN', 'label' => Mage::helper('simistorelocator')->__('Mongolian')),
            array('value' => 'ne_NP', 'label' => Mage::helper('simistorelocator')->__('Nepali')),
            array('value' => 'pa_IN', 'label' => Mage::helper('simistorelocator')->__('Punjabi')),
            array('value' => 'rm_CH', 'label' => Mage::helper('simistorelocator')->__('Romansh')),
            array('value' => 'sa_IN', 'label' => Mage::helper('simistorelocator')->__('Sanskrit')),
            array('value' => 'sr_RS', 'label' => Mage::helper('simistorelocator')->__('Serbian')),
            array('value' => 'so_SO', 'label' => Mage::helper('simistorelocator')->__('Somali')),
            array('value' => 'sw_KE', 'label' => Mage::helper('simistorelocator')->__('Swahili')),
            array('value' => 'tl_PH', 'label' => Mage::helper('simistorelocator')->__('Filipino')),
            array('value' => 'ta_IN', 'label' => Mage::helper('simistorelocator')->__('Tamil')),
            array('value' => 'tt_RU', 'label' => Mage::helper('simistorelocator')->__('Tatar')),
            array('value' => 'te_IN', 'label' => Mage::helper('simistorelocator')->__('Telugu')),
            array('value' => 'ml_IN', 'label' => Mage::helper('simistorelocator')->__('Malayalam')),
            array('value' => 'uk_UA', 'label' => Mage::helper('simistorelocator')->__('Ukrainian')),
            array('value' => 'uz_UZ', 'label' => Mage::helper('simistorelocator')->__('Uzbek')),
            array('value' => 'vi_VN', 'label' => Mage::helper('simistorelocator')->__('Vietnamese')),
            array('value' => 'xh_ZA', 'label' => Mage::helper('simistorelocator')->__('Xhosa')),
            array('value' => 'zu_ZA', 'label' => Mage::helper('simistorelocator')->__('Zulu')),
            array('value' => 'km_KH', 'label' => Mage::helper('simistorelocator')->__('Khmer')),
            array('value' => 'tg_TJ', 'label' => Mage::helper('simistorelocator')->__('Tajik')),
            array('value' => 'ar_AR', 'label' => Mage::helper('simistorelocator')->__('Arabic')),
            array('value' => 'he_IL', 'label' => Mage::helper('simistorelocator')->__('Hebrew')),
            array('value' => 'ur_PK', 'label' => Mage::helper('simistorelocator')->__('Urdu')),
            array('value' => 'fa_IR', 'label' => Mage::helper('simistorelocator')->__('Persian')),
            array('value' => 'sy_SY', 'label' => Mage::helper('simistorelocator')->__('Syriac')),
            array('value' => 'yi_DE', 'label' => Mage::helper('simistorelocator')->__('Yiddish')),
            array('value' => 'gn_PY', 'label' => Mage::helper('simistorelocator')->__('Guarani')),
            array('value' => 'qu_PE', 'label' => Mage::helper('simistorelocator')->__('Quechua')),
            array('value' => 'ay_BO', 'label' => Mage::helper('simistorelocator')->__('Aymara')),
            array('value' => 'se_NO', 'label' => Mage::helper('simistorelocator')->__('Northern Sami')),
            array('value' => 'ps_AF', 'label' => Mage::helper('simistorelocator')->__('Pashto')),
            array('value' => 'tl_ST', 'label' => Mage::helper('simistorelocator')->__('Klingon')),
        );
        return $options;
    }

}